Ci test python wrapper
3MAH/simcoon pull request #15
Opened 2024-09-27 10:38 UTC by chemiskyy

2024-09-27 14:08 UTC, kmarchais requested changes
Added a few suggestion to try to solve the CI issue.

Be carefull, even though the Windows CI is marked as passed, it's not working neither.

2024-09-27 14:08 UTC, kmarchais commented on .github/workflows/ci.yml
> +          sudo cmake --install . --config Release
```suggestion
          cmake --install build --config Release          
```

2024-09-27 14:08 UTC, kmarchais commented on .github/workflows/ci.yml
> +          python -m pip install .
```suggestion
          cmake -S simcoon-python-builder -B simcoon-python-builder/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INCLUDE_PATH=$CONDA_PREFIX/include -DCMAKE_LIBRARY_PATH=$CONDA_PREFIX/lib -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -Wno-dev
          cmake --build simcoon-python-builder/build
          python -m pip install python-setup
```

2024-09-27 20:54 UTC, chemiskyy commented
> Be carefull, even though the Windows CI is marked as passed, it's not working neither.

You are right, and we should ensure that Windows CI is working properly, thanks

2024-09-30 10:32 UTC, kmarchais commented
- Added `ninja` to the Linux and MacOS CI to build faster
- Replaced `cmd` by `pwsh` for the Windows CI

2024-10-16 07:20 UTC, merged